version: "3"
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: inert/inventar:new
    container_name: focalboard
    volumes:
      - fbdata:/opt/focalboard/data
    ports:
      - 80:8000
    environment:
      - TARGETOS=linux
      - VIRTUAL_PORT=8000

volumes:
  fbdata:
